version: '3'
services:
  api:
    build: 
      context: ./week_in_review/api
      dockerfile: ./Dockerfile_api.prod
    volumes:
      - ./week_in_review/api:/api:cached
    stdin_open: true # docker run -i
    tty: true # docker run -t
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    hostname: api
    depends_on:
      - postgres
      - data
    links:
      - postgres:postgres
    ports:
      - 85:80
    networks:
      ncaab_net_v2:
        ipv4_address: 172.02.3.4


  data:
    build:
      context: ./week_in_review/data
      dockerfile: ./Dockerfile_data.dev
    volumes:
      - ./week_in_review/data:/data:cached
    stdin_open: true # docker run -i
    tty: true # docker run -t
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    hostname: data
    depends_on:
      - postgres
    links:
      - postgres:postgres
    networks:
      ncaab_net_v2:
        ipv4_address: 172.02.3.2

  postgres:
    image: postgres
    hostname: postgres
    restart: always
    volumes:
      - ./week_in_review/db/raw:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      ncaab_net_v2:
        ipv4_address: 172.02.3.3

  
  frontend:
    build:
      context: ./week_in_review/frontend
      dockerfile: ./Dockerfile_vue.prod
    volumes:
      # Mount the root folder that contains .git
      #- ./frontend:/ncaab_vue_frontend:cached
      - ./week_in_review/frontend/frontend_nginx:/etc/nginx/conf.d
    ports:
      - 80:80
    links:
      - "api:api"
    depends_on:
      - api
    networks:
      ncaab_net_v2:
        ipv4_address: 172.02.3.5
    stdin_open: true # docker run -i
    tty: true # docker run -t
  
networks:
  ncaab_net_v2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.02.3.0/24
          gateway: 172.02.3.1



