version: '3.4'
services:
  api:
    build: 
      network: host
      context: ./api
      dockerfile: ./Dockerfile_api.prod
    image: ncaab_django_api_prod
    volumes:
      # Mount the root folder that contains .git
      - ./api:/ncaab
    environment:
      - ALLOWED_HOST=ncaab-api.winecoffeewifi.com
      - ALLOWED_ORIGIN=ncaab.winecoffeewifi.com
      - ENV_NAME=prod
    networks:
      vmdockernetwork:
        ipv4_address: 10.8.29.201
    stdin_open: true # docker run -i
    tty: true # docker run -t
  api-server:
    image: nginx
    volumes:
      - ./api_nginx:/etc/nginx/conf.d
    networks:
      vmdockernetwork:
        ipv4_address: 10.8.29.202
    stdin_open: true # docker run -i
    tty: true # docker run -t
  frontend:
    build:
      network: host
      context: ./frontend
      dockerfile: ./Dockerfile_vue.prod
    image: ncaab_vue_frontend_prod
    volumes:
      # Mount the root folder that contains .git
      #- ./frontend:/ncaab_vue_frontend:cached
      - ./frontend/frontend_nginx:/etc/nginx/conf.d
    networks:
      vmdockernetwork:
        ipv4_address: 10.8.29.203
    stdin_open: true # docker run -i
    tty: true # docker run -t
networks:
  vmdockernetwork:
    external: true


