version: '3.4'
services:
  api:
    build: 
      network: host
      context: ./api
      dockerfile: ./Dockerfile_api.prod
    image: ncaab_django_api_prod
    volumes:
      # Mount the root folder that contains .git
      - ../volume_api:/usr/app/venv/ncaab
    environment:
      - ALLOWED_HOST=ncaab-api.winecoffeewifi.com
      - ALLOWED_ORIGIN=ncaab.winecoffeewifi.com
      - ENV_NAME=prod
    networks:
      vmdockernetwork:
        ipv4_address: 10.8.29.201
    stdin_open: true # docker run -i
    tty: true # docker run -t
  api-server:
    image: nginx
    volumes:
      - ../api_nginx:/etc/nginx/conf.d
    networks:
      vmdockernetwork:
        ipv4_address: 10.8.29.202
    stdin_open: true # docker run -i
    tty: true # docker run -t
  frontend:
    build:
      network: host
      context: ./frontend
      dockerfile: ./Dockerfile_vue.prod
    image: ncaab_vue_frontend_prod
    volumes:
      # Mount the root folder that contains .git
      #- ./frontend:/ncaab_vue_frontend:cached
      - ./frontend/frontend_nginx:/etc/nginx/conf.d
    networks:
      vmdockernetwork:
        ipv4_address: 10.8.29.203
    stdin_open: true # docker run -i
    tty: true # docker run -t
networks:
  vmdockernetwork:
    external: true
#named volumes dont overrive#
#https://forums.docker.com/t/dockerfile-copy-command-not-copying-files/81520/4
#If you need to preserve files from the target folder, you will need to use a named volume, as its default behavior is to copy per-existing files into the volume.
#create a named volume using the local driver of the type bind.
volumes:
  api_source:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ubuntu/docker_containers/ncaab_week_in_review/api_source'
  api_server_conf:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ubuntu/docker_containers/ncaab_week_in_review/nginx/api_server'
  frontend_server_conf:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/ubuntu/docker_containers/ncaab_week_in_review/nginx/frontend_server'


