version: '3'
services:
  data:
    build:
      context: ./week_in_review/data
      dockerfile: ./Dockerfile_data.dev
    volumes:
      - ./week_in_review/data:/data:cached
    stdin_open: true # docker run -i
    tty: true # docker run -t
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    hostname: data
    depends_on:
      - postgres
    links:
      - postgres:postgres
    networks:
      ncaab_net_v2:
        ipv4_address: 172.02.2.2

  postgres:
    image: postgres
    hostname: postgres
    restart: always
    volumes:
      - ./week_in_review/db/raw:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    networks:
      ncaab_net_v2:
        ipv4_address: 172.02.2.3

  
  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: ./Dockerfile_vue.dev
  #   image: ncaab_vue_frontend
  #   volumes:
  #     # Mount the root folder that contains .git
  #     - ./frontend:/ncaab_vue_frontend:cached
  #   ports:
  #     - 8080:8080
  #   environment: 
  #     - CHOKIDAR_USEPOLLING=true #should enable hot reloading
  #     - BACKEND_API_ADDRESS=172.20.2.4
  #   links:
  #     - "api:pwd_django_api"
  #   networks:
  #     ncaab_net:
  #       ipv4_address: 172.89.2.3
  #   stdin_open: true # docker run -i
  #   tty: true # docker run -t
  
networks:
  ncaab_net_v2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.02.2.0/24
          gateway: 172.02.2.1



