FROM node:16-slim
WORKDIR /frontend
# copy both 'package.json' and 'package-lock.json' (if available)
COPY ncaab_vue_frontend/package*.json /frontend

# install project dependencies
RUN npm install

# copy project files and folders to the current working directory (i.e. 'app' folder)
COPY ./ncaab_vue_frontend /frontend

EXPOSE 8080
#CMD npm run serve
