# Generated by Django 4.0.2 on 2022-02-23 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inter_WeekResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team_Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_date', models.CharField(max_length=200)),
                ('final_score', models.IntegerField(null=True)),
                ('opponent_final_score', models.IntegerField(null=True)),
                ('is_win', models.BooleanField(default=False, null=True)),
                ('is_home', models.BooleanField(default=False, null=True)),
                ('is_neutral_court', models.BooleanField(default=False, null=True)),
                ('is_overtime', models.BooleanField(default=False, null=True)),
                ('cancelled_or_postponed', models.BooleanField(null=True)),
                ('game_time', models.CharField(max_length=200, null=True)),
                ('tv', models.CharField(max_length=200, null=True)),
            ],
            options={
                'db_table': 'team_schedule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Team_Week_Rankings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField()),
            ],
            options={
                'db_table': 'team_week_rankings',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('espn_team_id', models.IntegerField(primary_key=True, serialize=False)),
                ('team_name', models.CharField(max_length=200)),
                ('logo_url', models.TextField(null=True)),
                ('team_page_url', models.TextField(null=True)),
            ],
            options={
                'db_table': 'teams',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TopWeekResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('espn_team_id', models.IntegerField()),
                ('team_name', models.CharField(max_length=200)),
                ('opponent_espn_team_id', models.IntegerField()),
                ('opponent_team_name', models.CharField(max_length=200)),
                ('game_date', models.CharField(max_length=200)),
                ('final_score', models.IntegerField(null=True)),
                ('opponent_final_score', models.IntegerField(null=True)),
                ('is_win', models.BooleanField(default=False, null=True)),
                ('is_home', models.BooleanField(default=False, null=True)),
                ('is_neutral_court', models.BooleanField(default=False, null=True)),
                ('is_overtime', models.BooleanField(default=False, null=True)),
                ('cancelled_or_postponed', models.BooleanField(null=True)),
                ('game_time', models.CharField(max_length=200, null=True)),
                ('tv', models.CharField(max_length=200, null=True)),
                ('week_number', models.IntegerField()),
                ('start_date_inclusive', models.CharField(max_length=200)),
                ('end_date_exclusive', models.CharField(max_length=200)),
                ('is_current_week', models.BooleanField(default=False)),
                ('ranking', models.IntegerField()),
                ('opponent_ranking', models.IntegerField()),
                ('logo_url', models.TextField(null=True)),
                ('opponent_logo_url', models.TextField(null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('week_number', models.IntegerField(primary_key=True, serialize=False)),
                ('start_date_inclusive', models.CharField(max_length=200)),
                ('end_date_exclusive', models.CharField(max_length=200)),
                ('is_current_week', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'weeks',
                'managed': False,
            },
        ),
    ]
